
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class simbolos {
  /* terminals */
  public static final int sstring = 10;
  public static final int id = 11;
  public static final int imprimir = 8;
  public static final int EOF = 0;
  public static final int menos = 6;
  public static final int numero = 9;
  public static final int error = 1;
  public static final int parc = 3;
  public static final int negativo = 7;
  public static final int mas = 5;
  public static final int pyc = 4;
  public static final int para = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "para",
  "parc",
  "pyc",
  "mas",
  "menos",
  "negativo",
  "imprimir",
  "numero",
  "sstring",
  "id"
  };
}

